### ISSUE TITLE
Post/Project Meta Data

### ISSUE THREAD

**Issue by daveaseeman** [daveas/daveas.github.io#27]
**Tags:**
- [ ] add projects to tags.html (tabbed projects/posts)

**Categories:**
- [ ] create categories.html for listing categories  (tabbed projects/posts)

**Projects:**
- [ ] add images to project listing
- [ ] create icons for each tag in projects
- [ ] add icons on project page (material, ruby, etc)

**Comment by daveas** [comment]
[ ] change tags.html to navigation.html
[ ]

**Comment by daveaseeman** [comment]
possible icon for categories:

``` html
<i class="fa fa-briefcase"></i>
<i class="fa fa-suitcase"></i>
<i class="fa fa-sitemap"></i>
<i class="fa fa-folder"></i>
<i class="fa fa-folder-open"></i>
```

**Comment by daveaseeman** [comment]
engineering `<i class="fa fa-cogs"></i>`
design `<i class="fa fa-cube"></i>` or `<i class="fa fa-pencil"></i>` or `<i class="fa fa-eye"></i>`
business `<i class="fa fa-briefcase"></i>` or `<i class="fa fa-building"></i>`
productivity `<i class="fa fa-level-up"></i>` or `<i class="fa fa-coffee"></i>` or `<i class="fa fa-bolt"></i>`

**Comment by daveaseeman** [comment]
? change productivity to:
- optimization
- experimentation
- testing
- performance
- growth
